export const BOARD_SIZE = 3;
export const WIN_MARKS_COUNT = BOARD_SIZE; // different value not supported right now
export const CELL_BG_COLOR_DEFAULT = '#fff';
export const CELL_BG_COLOR_WON = '#0f0';
export const CELL_MARK_DEFAULT = '';
export const CELL_MARK_USER = 'X';
export const CELL_MARK_COMP = 'O';
export const COMPUTER_SPEED = 500;
export const LOCAL_STORAGE_KEY = 'tic-tac-toe-forever';
